# Generated by Django 3.1.3 on 2020-12-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201124_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='derscription',
            new_name='description',
        ),
    ]
